### ISSUE TITLE
add detail docs

### ISSUE THREAD

**Issue by auvipy** [FlipperPA/wagtailpress#1]

**Comment by FlipperPA** [comment]
This is on the to-do list, but this is very much in alpha. Any interest in contributing?

**Comment by auvipy** [comment]
how can I help?

**Comment by auvipy** [comment]
django-zinia-blog could be a reference to take inspiration?

**Comment by FlipperPA** [comment]
Sorry for the delay in reply. I'll be working on this over the next few days. Things are still very much in flux, so until some design decisions are made, documentation won't be in place.

**Comment by auvipy** [comment]
look at puput a alternative for this
